User.create(username: "alex", password: "yolo")
User.create(username: "sahan", password: "yolo")
User.create(username: "nirav", password: "yolo")
User.create(username: "neal", password: "yolo")
User.create(username: "mario", password: "yolo")

Survey.create(title: "Alex's Survey", user_id: 1)
Survey.create(title: "Sahan's Survey", user_id: 2)
Survey.create(title: "Nirav's Survey", user_id: 3)
Survey.create(title: "Neal's Survey", user_id: 4)
Survey.create(title: "Mario's Survey", user_id: 5)

Question.create(question: "What is your favorite food?", survey_id: 1)
Question.create(question: "What is your favorite drink?", survey_id: 1)
Question.create(question: "What is your favorite pokemon?", survey_id: 1)

Question.create(question: "What is your favorite food?", survey_id: 2)
Question.create(question: "What is your favorite drink?", survey_id: 2)
Question.create(question: "What is your favorite pokemon?", survey_id: 2)

Question.create(question: "What is your favorite food?", survey_id: 3)
Question.create(question: "What is your favorite drink?", survey_id: 3)
Question.create(question: "What is your favorite pokemon?", survey_id: 3)

Question.create(question: "What is your favorite food?", survey_id: 4)
Question.create(question: "What is your favorite drink?", survey_id: 4)
Question.create(question: "What is your favorite pokemon?", survey_id: 4)

Question.create(question: "What is your favorite food?", survey_id:5)
Question.create(question: "What is your favorite drink?", survey_id:5)
Question.create(question: "What is your favorite pokemon?", survey_id: 5)

Choice.create(choice: "Pizza", question_id: 1)
Choice.create(choice: "Hamburgers", question_id: 1)
Choice.create(choice: "Hotdogs", question_id: 1)

Choice.create(choice: "Beer", question_id: 2)
Choice.create(choice: "Wine", question_id: 2)
Choice.create(choice: "Hard Alcohol", question_id: 2)

Choice.create(choice: "Venusaur", question_id: 3)
Choice.create(choice: "Blastoise", question_id: 3)
Choice.create(choice: "Charizard", question_id: 3)

Choice.create(choice: "Pizza", question_id: 4)
Choice.create(choice: "Hamburgers", question_id: 4)
Choice.create(choice: "Hotdogs", question_id: 4)

Choice.create(choice: "Beer", question_id: 5)
Choice.create(choice: "Wine", question_id: 5)
Choice.create(choice: "Hard Alcohol", question_id: 5)

Choice.create(choice: "Venusaur", question_id: 6)
Choice.create(choice: "Blastoise", question_id: 6)
Choice.create(choice: "Charizard", question_id: 6)

Choice.create(choice: "Pizza", question_id: 7)
Choice.create(choice: "Hamburgers", question_id: 7)
Choice.create(choice: "Hotdogs", question_id: 7)

Choice.create(choice: "Beer", question_id: 8)
Choice.create(choice: "Wine", question_id: 8)
Choice.create(choice: "Hard Alcohol", question_id: 8)

Choice.create(choice: "Venusaur", question_id: 9)
Choice.create(choice: "Blastoise", question_id: 9)
Choice.create(choice: "Charizard", question_id: 9)

Choice.create(choice: "Pizza", question_id: 10)
Choice.create(choice: "Hamburgers", question_id: 10)
Choice.create(choice: "Hotdogs", question_id: 10)

Choice.create(choice: "Beer", question_id: 11)
Choice.create(choice: "Wine", question_id: 11)
Choice.create(choice: "Hard Alcohol", question_id: 11)

Choice.create(choice: "Venusaur", question_id: 12)
Choice.create(choice: "Blastoise", question_id: 12)
Choice.create(choice: "Charizard", question_id: 12)

Choice.create(choice: "Pizza", question_id: 13)
Choice.create(choice: "Hamburgers", question_id: 13)
Choice.create(choice: "Hotdogs", question_id: 13)

Choice.create(choice: "Beer", question_id: 14)
Choice.create(choice: "Wine", question_id: 14)
Choice.create(choice: "Hard Alcohol", question_id: 14)

Choice.create(choice: "Venusaur", question_id: 15)
Choice.create(choice: "Blastoise", question_id: 15)
Choice.create(choice: "Charizard", question_id: 15)

SurveyedUser.create(user_id: 1, survey_id: 1)
SurveyedUser.create(user_id: 1, survey_id: 2)
SurveyedUser.create(user_id: 1, survey_id: 3)
SurveyedUser.create(user_id: 1, survey_id: 4)
SurveyedUser.create(user_id: 1, survey_id: 5)

SurveyedUser.create(user_id: 2, survey_id: 1)
SurveyedUser.create(user_id: 2, survey_id: 2)
SurveyedUser.create(user_id: 2, survey_id: 3)
SurveyedUser.create(user_id: 2, survey_id: 4)
SurveyedUser.create(user_id: 2, survey_id: 5)

SurveyedUser.create(user_id: 3, survey_id: 1)
SurveyedUser.create(user_id: 3, survey_id: 2)
SurveyedUser.create(user_id: 3, survey_id: 3)
SurveyedUser.create(user_id: 3, survey_id: 4)
SurveyedUser.create(user_id: 3, survey_id: 5)

SurveyedUser.create(user_id: 4, survey_id: 1)
SurveyedUser.create(user_id: 4, survey_id: 2)
SurveyedUser.create(user_id: 4, survey_id: 3)
SurveyedUser.create(user_id: 4, survey_id: 4)
SurveyedUser.create(user_id: 4, survey_id: 5)

SurveyedUser.create(user_id: 5, survey_id: 1)
SurveyedUser.create(user_id: 5, survey_id: 2)
SurveyedUser.create(user_id: 5, survey_id: 3)
SurveyedUser.create(user_id: 5, survey_id: 4)
SurveyedUser.create(user_id: 5, survey_id: 5)

Response.create(choice_id: 2, surveyed_user_id: 1)
Response.create(choice_id: 4, surveyed_user_id: 1)
Response.create(choice_id: 9, surveyed_user_id: 1)
Response.create(choice_id: 10, surveyed_user_id: 2)
Response.create(choice_id: 13, surveyed_user_id: 2)
Response.create(choice_id: 17, surveyed_user_id: 2)
Response.create(choice_id: 20, surveyed_user_id: 3)
Response.create(choice_id: 23, surveyed_user_id: 3)
Response.create(choice_id: 25, surveyed_user_id: 3)
Response.create(choice_id: 30, surveyed_user_id: 4)
Response.create(choice_id: 33, surveyed_user_id: 4)
Response.create(choice_id: 36, surveyed_user_id: 4)
Response.create(choice_id: 39, surveyed_user_id: 5)
Response.create(choice_id: 40, surveyed_user_id: 5)
Response.create(choice_id: 44, surveyed_user_id: 5)

Response.create(choice_id: 2, surveyed_user_id: 6)
Response.create(choice_id: 4, surveyed_user_id: 6)
Response.create(choice_id: 9, surveyed_user_id: 6)
Response.create(choice_id: 10, surveyed_user_id: 7)
Response.create(choice_id: 13, surveyed_user_id: 7)
Response.create(choice_id: 17, surveyed_user_id: 7)
Response.create(choice_id: 20, surveyed_user_id: 8)
Response.create(choice_id: 23, surveyed_user_id: 8)
Response.create(choice_id: 25, surveyed_user_id: 8)
Response.create(choice_id: 30, surveyed_user_id: 9)
Response.create(choice_id: 33, surveyed_user_id: 9)
Response.create(choice_id: 36, surveyed_user_id: 9)
Response.create(choice_id: 39, surveyed_user_id: 10)
Response.create(choice_id: 40, surveyed_user_id: 10)
Response.create(choice_id: 44, surveyed_user_id: 10)

Response.create(choice_id: 2, surveyed_user_id: 11)
Response.create(choice_id: 4, surveyed_user_id: 11)
Response.create(choice_id: 9, surveyed_user_id: 11)
Response.create(choice_id: 10, surveyed_user_id: 12)
Response.create(choice_id: 13, surveyed_user_id: 12)
Response.create(choice_id: 17, surveyed_user_id: 12)
Response.create(choice_id: 20, surveyed_user_id: 13)
Response.create(choice_id: 23, surveyed_user_id: 13)
Response.create(choice_id: 25, surveyed_user_id: 13)
Response.create(choice_id: 30, surveyed_user_id: 14)
Response.create(choice_id: 33, surveyed_user_id: 14)
Response.create(choice_id: 36, surveyed_user_id: 14)
Response.create(choice_id: 39, surveyed_user_id: 15)
Response.create(choice_id: 40, surveyed_user_id: 15)
Response.create(choice_id: 44, surveyed_user_id: 15)

Response.create(choice_id: 2, surveyed_user_id: 16)
Response.create(choice_id: 4, surveyed_user_id: 16)
Response.create(choice_id: 9, surveyed_user_id: 16)
Response.create(choice_id: 10, surveyed_user_id: 17)
Response.create(choice_id: 13, surveyed_user_id: 17)
Response.create(choice_id: 17, surveyed_user_id: 17)
Response.create(choice_id: 20, surveyed_user_id: 18)
Response.create(choice_id: 23, surveyed_user_id: 18)
Response.create(choice_id: 25, surveyed_user_id: 18)
Response.create(choice_id: 30, surveyed_user_id: 19)
Response.create(choice_id: 33, surveyed_user_id: 19)
Response.create(choice_id: 36, surveyed_user_id: 19)
Response.create(choice_id: 39, surveyed_user_id: 20)
Response.create(choice_id: 40, surveyed_user_id: 20)
Response.create(choice_id: 44, surveyed_user_id: 20)

Response.create(choice_id: 2, surveyed_user_id: 21)
Response.create(choice_id: 4, surveyed_user_id: 21)
Response.create(choice_id: 9, surveyed_user_id: 21)
Response.create(choice_id: 10, surveyed_user_id: 22)
Response.create(choice_id: 13, surveyed_user_id: 22)
Response.create(choice_id: 17, surveyed_user_id: 22)
Response.create(choice_id: 20, surveyed_user_id: 23)
Response.create(choice_id: 23, surveyed_user_id: 23)
Response.create(choice_id: 25, surveyed_user_id: 23)
Response.create(choice_id: 30, surveyed_user_id: 24)
Response.create(choice_id: 33, surveyed_user_id: 24)
Response.create(choice_id: 36, surveyed_user_id: 24)
Response.create(choice_id: 39, surveyed_user_id: 25)
Response.create(choice_id: 40, surveyed_user_id: 25)
Response.create(choice_id: 44, surveyed_user_id: 25)
